### NUMPY

In [1]:
# Import NumPy as its abbreviation 'np'

import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()

a1 = np.array ([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [3]:
a1.ndim

1

In [4]:
# Create a 2-dimensional NumPy array using np.array()

a2 = np.array ([[1,2,3],
              [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a2.ndim

2

In [6]:
# Create a 3-dimensional Numpy array using np.array()

a3 = np.array ([[[1,2,3,3], [6,9,0,2], [4,5,6,4], [5,6,7,1]], [[7,5,1,8], [2,3,5,4], [1,2,2,1], [7,8,9,3]]])
a3

array([[[1, 2, 3, 3],
        [6, 9, 0, 2],
        [4, 5, 6, 4],
        [5, 6, 7, 1]],

       [[7, 5, 1, 8],
        [2, 3, 5, 4],
        [1, 2, 2, 1],
        [7, 8, 9, 3]]])

In [7]:
a3.ndim

3

In [8]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)

In [9]:
a1.shape, a1.size, a1.dtype, type(a1)

((5,), 5, dtype('int32'), numpy.ndarray)

In [10]:
# Attributes of 2-dimensional array

a2.shape, a2.size, a2.dtype, type (a2)

((2, 3), 6, dtype('int32'), numpy.ndarray)

In [11]:
# Attributes of 3-dimensional array

a3.shape, a3.size, a3.dtype, type (a3)

((2, 4, 4), 32, dtype('int32'), numpy.ndarray)

In [12]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created

import pandas as pd

my_pandas = pd.DataFrame (a2)
my_pandas

0  1  2
0  1  2  3
1  4  5  6

In [13]:
# Create an array of shape (10, 2) with only ones

an_array = np.ones ((10, 2))
an_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
# Create an array of shape (7, 2, 3) of only zeros

an_array2  = np.zeros ((7, 2, 3))
an_array2

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [15]:
# Create an array within a range of 0 and 100 with step 3

an_array3 = np.array(range(0, 100, 3))
an_array3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

Or

In [16]:
an_array33 = np.arange(0, 100, 3)
an_array33

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [17]:
# Create a random array with numbers between 0 and 10 of size (7, 2)

an_array4 = np.random.randint(10, size = (7, 2))
an_array4

array([[7, 3],
       [1, 3],
       [2, 8],
       [0, 2],
       [9, 0],
       [2, 6],
       [9, 9]])

In [18]:
# Create a random array of floats between 0 & 1 of shape (3, 5)

an_array5 = np.random.random((3, 5))
an_array5

array([[0.91391519, 0.20246652, 0.03651879, 0.9877896 , 0.80903264],
       [0.96548337, 0.67831903, 0.91632238, 0.9499054 , 0.12693901],
       [0.65186439, 0.44451777, 0.04685385, 0.71686814, 0.47245521]])

In [19]:
# Set the random seed to 42
# Create a random array of numbers between 0 & 10 of size (4, 6)

np.random.seed (42)

an_array6 = np.random.randint (10, size= (4, 6))
an_array6

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [20]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
# Find the unique numbers in the array you just created

an_array7 = np.random.randint (10, size =(3, 7))
an_array7

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6],
       [1, 3, 8, 1, 9, 8, 9]])

In [21]:
np.unique(an_array7)

array([0, 1, 2, 3, 4, 6, 8, 9])

In [22]:
# Find the 0'th index of the latest array you created

an_array7[0]

array([8, 0, 9, 2, 6, 3, 8])

In [23]:
# Get the first 2 rows of latest array you created

an_array7 [0:2]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [24]:
# Get the first 2 values of the first 2 rows of the latest array

an_array7 [0:2, 0:2]

array([[8, 0],
       [2, 4]])

In [25]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

an_array8 = np.random.randint(10, size = (3, 5))
an_array9 = np.ones ((3, 5))

In [26]:
an_array8

array([[4, 1, 3, 6, 7],
       [2, 0, 3, 1, 7],
       [3, 1, 5, 5, 9]])

In [27]:
an_array9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
# Add the two arrays together

an_array8 + an_array9

array([[ 5.,  2.,  4.,  7.,  8.],
       [ 3.,  1.,  4.,  2.,  8.],
       [ 4.,  2.,  6.,  6., 10.]])

In [29]:
# Create another array of ones of shape (5, 3)

a10 = np.ones ((5,3))
a10

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
an_array9 + a10

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [31]:
a11= an_array9 + a10.reshape (3, 5)
a11

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [32]:
# Create another array of ones of shape (3, 5)

a12 = np.random.randint (10, size = (3, 5)) 
a12

array([[3, 5, 1, 9, 1],
       [9, 3, 7, 6, 8],
       [7, 4, 1, 4, 7]])

In [33]:
# Subtract the new array of ones from the other most recent array

a13 = a12-an_array9
a13

array([[2., 4., 0., 8., 0.],
       [8., 2., 6., 5., 7.],
       [6., 3., 0., 3., 6.]])

In [34]:
# Multiply the ones array with the latest array

a14 = an_array9 * a13
a14

array([[2., 4., 0., 8., 0.],
       [8., 2., 6., 5., 7.],
       [6., 3., 0., 3., 6.]])

In [35]:
# Take the latest array to the power of 2 using '**'
a14 ** 2

array([[ 4., 16.,  0., 64.,  0.],
       [64.,  4., 36., 25., 49.],
       [36.,  9.,  0.,  9., 36.]])

In [36]:
# Do the same thing with np.square()

a15 = np.square (a14)
a15

array([[ 4., 16.,  0., 64.,  0.],
       [64.,  4., 36., 25., 49.],
       [36.,  9.,  0.,  9., 36.]])

In [37]:
# Find the mean of the latest array using np.mean()

a16 = np.mean (a15)
a16

23.466666666666665

In [38]:
# Find the maximum of the latest array using np.max()

np.max (a15)

64.0

In [39]:
# Find the minimum of the latest array using np.min()

np.min (a15)

0.0

In [40]:
# Find the standard deviation of the latest array

np.std(a15)

22.054074957300347

In [41]:
# Find the variance of the latest array

np.var(a15)

486.3822222222223

In [42]:
# Reshape the latest array to (3, 5, 1)

a15.reshape (3,5,1)

array([[[ 4.],
        [16.],
        [ 0.],
        [64.],
        [ 0.]],

       [[64.],
        [ 4.],
        [36.],
        [25.],
        [49.]],

       [[36.],
        [ 9.],
        [ 0.],
        [ 9.],
        [36.]]])

In [43]:
a15.T

array([[ 4., 64., 36.],
       [16.,  4.,  9.],
       [ 0., 36.,  0.],
       [64., 25.,  9.],
       [ 0., 49., 36.]])

In [44]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)

a20 = np.random.randint (10, size = (3, 3))
a21 = np.random.randint (10, size = (3, 2))

In [45]:
a20

array([[9, 8, 8],
       [0, 8, 6],
       [8, 7, 0]])

In [46]:
a21

array([[7, 7],
       [2, 0],
       [7, 2]])

In [47]:
# Perform a dot product on the two newest arrays you created

np.dot(a20, a21)

array([[135,  79],
       [ 58,  12],
       [ 70,  56]])

In [48]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)

a22 = np.random.randint (10, size = (4, 3))
a23 = np.random.randint (10, size = (4, 3))

In [49]:
a22

array([[2, 0, 4],
       [9, 6, 9],
       [8, 6, 8],
       [7, 1, 0]])

In [50]:
a23

array([[6, 6, 7],
       [4, 2, 7],
       [5, 2, 0],
       [2, 4, 2]])

In [51]:
np.dot (a22, a23)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [52]:
# Take the latest two arrays, perform a transpose on one of them and then perfoa dot product on them both

np.dot (a22, a23.T)

array([[ 40,  36,  10,  12],
       [153, 111,  57,  60],
       [140, 100,  52,  56],
       [ 48,  30,  37,  18]])

In [53]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables

a30 = np.random.randint (10, size = (3, 5))
a31 = np.random.randint (10, size = (3, 5))

In [54]:
a30

array([[0, 4, 9, 6, 6],
       [8, 9, 9, 2, 6],
       [0, 3, 3, 4, 6]])

In [55]:
a31

array([[6, 3, 6, 2, 5],
       [1, 9, 8, 4, 5],
       [3, 9, 6, 8, 6]])

In [56]:
# Compare the two arrays with '>'

a30 > a31

array([[False,  True,  True,  True,  True],
       [ True, False,  True, False,  True],
       [False, False, False, False, False]])

In [57]:
# Compare the two arrays with '>='

a30 >= a31

array([[False,  True,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [False, False, False, False,  True]])

In [58]:
# Find which elements of the first array are greater than 7

a30 > 7

array([[False, False,  True, False, False],
       [ True,  True,  True, False, False],
       [False, False, False, False, False]])

In [59]:
# Which parts of each array are equal? (try using '==')

a30 == a31

array([[False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False,  True]])

In [60]:
# Sort one of the arrays you just created in ascending order

np.sort (a30)

array([[0, 4, 6, 6, 9],
       [2, 6, 8, 9, 9],
       [0, 3, 3, 4, 6]])

In [61]:
np.sort (a31)

array([[2, 3, 5, 6, 6],
       [1, 4, 5, 8, 9],
       [3, 6, 6, 8, 9]])

In [62]:
# Sort the indexes of one of the arrays you just created

np.argsort (a30)

array([[0, 1, 3, 4, 2],
       [3, 4, 0, 1, 2],
       [0, 1, 2, 3, 4]], dtype=int64)

In [63]:
np.argsort (a31)

array([[3, 1, 4, 0, 2],
       [0, 3, 4, 2, 1],
       [0, 2, 4, 3, 1]], dtype=int64)

In [64]:
# Find the index with the maximum value in one of the arrays you've created

np.argmax(a30)

2

In [65]:
np.argmax(a31)

6

In [66]:
# Find the index with the minimum value in one of the arrays you've created

np.argmin (a30)

0

In [67]:
np.argmin (a31)

5

In [68]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created

np.argmax(a30, axis = 1)

array([2, 1, 4], dtype=int64)

In [69]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created

np.argmin(a30, axis = 0)

array([0, 2, 2, 1, 0], dtype=int64)

In [70]:
# Create an array of normally distributed random numbers

np.random.randn (4, 3)

array([[-0.2581848 ,  0.46095562, -1.34938997],
       [-1.01907279,  0.12701224, -1.24944372],
       [ 1.94511561, -0.15333646, -0.90698723],
       [-0.81735416, -0.48312268, -0.56982835]])

In [71]:
# Create an array with 10 evenly spaced numbers between 1 and 100

np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])